[options]
admin_passwd = $pbkdf2-sha512$600000$9L4XwrgX4vxfCwFAyHlPCQ$PjYFZ6oJ8nYgrc7y7so7A.16L1nJqy7Vgod03ATmEiBwro8TpXy8Pkym4dzqyjQZFal7HUWznWZCLKXzZ52heA
db_host = localhost
db_port = 5432
db_user = odoo
db_password = postgres
db_template = template1
addons_path = addons,custom_addons

